name: FalloutRadiation
version: 1.0.0
api-version: 1.16
author: Exelo
main: fr.exelo.radiation.Main
depend: [WorldGuard]
commands:
  rad:
    description: Ceci est une commande qui permet de controler les radiations
    
permissions:
   rad.*:
     description: Donne toutes les permissions falloutradiation
     children:
       rad.use: true
   rad.use:
     description: Ceci est une permission pour controler les radiations
     default: false